### ISSUE TITLE
Services list endpoint is not paged

### ISSUE THREAD

**Issue by kiwiz** [banyansecurity/pybanyan#2]
The `client.services.list()` endpoint doesn't appear to support paging and will throw an error when trying to invoke it:
```
banyan.core.exc.BanyanError: 400 Client Error: Bad Request for url: https://net.banyanops.com/api/v1/registered_services?Skip=0&Limit=1000: Unknown key in request: Skip
```

The following monkey patch worked for me, for ref:
```
client.paged_request = client.api_request
```

**Comment by tradel** [comment]
The `/registered_services` API endpoint doesn't actually support paging yet:

```
GET /api/v1/registered_services
400 Bad Request
{
    "Message": "Unknown key in request: start"
}
```

**Comment by kiwiz** [comment]
Right, the problem is that the python client is broken because `list` internally calls `paged_request`.

**Comment by tradel** [comment]
Thanks @kiwiz. You're right, this was an oversight. I am fixing this by adding a new `supports_paging` parameter to the `Meta` subclass for each resource type, and new logic to select `paged_request` or `api_request` depending on the value of the parameter.
