### ISSUE TITLE
sync-aws command pulls in terminated ec2 instances

### ISSUE THREAD

**Issue by fjamal15** [banyansecurity/pybanyan#39]
Could be the same for RDS, and ALBs but have not tested

**Comment by tdesikan** [comment]
Thanks for reporting. Fixing in this PR:

https://github.com/banyansecurity/pybanyan/pull/38

ELB and RDS resources are treated differently (more "permanently"?) than EC2 instances, so AWS doesn't retain terminated ones in the list view.

**Comment by tdesikan** [comment]
fixed in 0.27.1
